In [3]:
import numpy as np

In [4]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [5]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [6]:
print(y)

[[0]
 [1]
 [1]
 [0]]


In [7]:
#Step 2 build model

num_epochs = 60000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [8]:
print(syn0)

[[-0.69212771  0.11456541  0.11586552 -0.67837065]
 [-0.0442175   0.14152761  0.99966035 -0.40354756]
 [ 0.25109093  0.87791118 -0.79088494 -0.33079323]]


In [9]:
print(syn1)

[[-0.84613925]
 [ 0.75156014]
 [-0.46419893]
 [ 0.93634808]]


In [10]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [11]:
#Step 3 Train Model

for j in range(num_epochs):
    #feed forward through layers 0,1, and 2
    k0 = x
    k1 = nonlin(np.dot(k0, syn0))
    k2 = nonlin(np.dot(k1, syn1))
    
    #how much did we miss the target value?
    k2_error = y - k2
    
    if j% 10000 == 0:
        print("Error:" + str(np.mean(np.abs(k2_error))))
    
    #in what direction is the target value?
    k2_delta = k2_error*nonlin(k2, deriv=True)
    
    #how much did each k1 value contribute to k2 error
    k1_error = k2_delta.dot(syn1.T)
    
    k1_delta= k1_error * nonlin(k1,deriv=True)
    
    syn1 += k1.T.dot(k2_delta)
    syn0 += k0.T.dot(k1_delta)

Error:0.5011382090888881
Error:0.010666767572575472
Error:0.007233172756550478
Error:0.0057827833704237564
Error:0.004938703725086441
Error:0.00437180844571566
